export const CONSTITUENCY_DEFAULT_WARD: Record<string, string> = {
  "Westlands": "Parklands/Highridge",
  "Dagoretti North": "Kilimani",
  "Dagoretti South": "Uthiru/Ruthimitu",
  "Langata": "Karen",
  "Kibra": "Laini Saba",
  "Roysambu": "Roysambu",
  "Kasarani": "Mwiki",
  "Ruaraka": "Lucky Summer",
  "Embakasi South": "Imara Daima",
  "Embakasi North": "Kariobangi North",
  "Embakasi Central": "Kayole North",
  "Embakasi East": "Upper Savannah",
  "Embakasi West": "Umoja I",
  "Makadara": "Maringo/Hamza",
  "Kamukunji": "Pumwani",
  "Starehe": "Nairobi Central",
  "Mathare": "Hospital",
  "Ruiru": "Gitothua",
  "Juja": "Kalimoni",
  "Thika Town": "Township",
  "Gatundu South": "Kiamwangi",
  "Gatundu North": "Githobokoni",
  "Githunguri": "Githunguri",
  "Kiambu": "Township",
  "Kiambaa": "Cianda",
  "Kabete": "Kabete",
  "Kikuyu": "Kikuyu",
  "Limuru": "Limuru Central",
  "Lari": "Lari/Kirenga",
  "Changamwe": "Chaani",
  "Jomvu": "Jomvu Kuu",
  "Kisauni": "Mjambere",
  "Nyali": "Kongowea",
  "Likoni": "Shika Adabu",
  "Mvita": "Mji Wa Kale/Makadara",
  "Kisumu East": "Kajulu",
  "Kisumu West": "Central Kisumu",
  "Kisumu Central": "Railways",
  "Seme": "West Seme",
  "Nyando": "Awasi/Onjiko",
  "Muhoroni": "Muhoroni/Koru",
  "Nyakach": "South West Nyakach",
  "Molo": "Molo",
  "Njoro": "Njoro",
  "Naivasha": "Naivasha East",
  "Gilgil": "Gilgil",
  "Kuresoi South": "Amalo",
  "Kuresoi North": "Kiptororo",
  "Subukia": "Subukia",
  "Rongai": "Menengai West",
  "Bahati": "Bahati",
  "Nakuru Town West": "Barut",
  "Nakuru Town East": "Biashara",
  "Kajiado North": "Olkeri",
  "Kajiado Central": "Purko",
  "Kajiado East": "Imaroro",
  "Kajiado West": "Keekonyokie",
  "Kajiado South": "Entonet/Lenkisim",
  "Masinga": "Masinga Central",
  "Yatta": "Matuu",
  "Kangundo": "Kangundo Central",
  "Matungulu": "Matungulu North",
  "Kathiani": "Kathiani Central",
  "Mavoko": "Athi River",
  "Machakos Town": "Machakos Central",
  "Mwala": "Kibauni",
  "Soy": "Soy",
  "Turbo": "Huruma",
  "Moiben": "Moiben",
  "Ainabkoi": "Ainabkoi/Olare",
  "Kapseret": "Langas",
  "Kesses": "Cheptiret/Kipchamo",
  "Kilifi North": "Dabaso",
  "Kilifi South": "Chasimba",
  "Kaloleni": "Kaloleni",
  "Rabai": "Kambe/Ribe",
  "Ganze": "Ganze",
  "Malindi": "Malindi Town",
  "Magarini": "Magarini",
  "Igembe South": "Maua",
  "Igembe Central": "Kangeta",
  "Igembe North": "Antuambui",
  "Tigania West": "Akithii",
  "Tigania East": "Karama",
  "North Imenti": "Municipality",
  "Buuri": "Timau",
  "Central Imenti": "Abothuguchi Central",
  "South Imenti": "Abogeta East",
  "Tetu": "Aguthi-Gaaki",
  "Kieni": "Naromoru Kiamathaga",
  "Mathira": "Karatina Town",
  "Othaya": "Chinga",
  "Mukurweini": "Mukurwe-Ini Central",
  "Nyeri Town": "Rware",
  "Kiharu": "Township",
  "Kigumo": "Kigumo",
  "Maragwa": "Ichagaki",
  "Kandara": "Gaichanjiru",
  "Gatanga": "Gatanga",
  "Mathioya": "Gitugi",
  "Kangema": "Kanyenya-Ini",
  "Mwea": "Mutithi",
  "Gichugu": "Kabare",
  "Ndia": "Mukure",
  "Kirinyaga Central": "Inoi",
  "Manyatta": "Gaturi South",
  "Runyenjes": "Kagaari South",
  "Mbeere South": "Kiambere",
  "Mbeere North": "Evurore",
  "Laikipia West": "Rumuruti Township",
  "Laikipia East": "Nanyuki",
  "Laikipia North": "Mugogodo East",
  "Kinangop": "Engineer",
  "Kipipiri": "Kipipiri",
  "Ol Kalou": "Kaimbaga",
  "Ol Jorok": "Charagita",
  "Ndaragwa": "Central",
  "Cherangany": "Cherangany/Suwerwa",
  "Endebess": "Endebess",
  "Saboti": "Saboti",
  "Kiminini": "Kiminini",
  "Kwanza": "Kwanza",
  "Webuye East": "Maraka",
  "Webuye West": "Misikhu",
  "Kanduyi": "Township",
  "Bumula": "Bumula",
  "Kabuchai": "Kabuchai/Chwele",
  "Mt. Elgon": "Cheptais",
  "Sirisia": "Malakisi/South Kulisiru",
  "Tongaren": "Tongaren",
  "Kimilili": "Kimilili",
  "Lugari": "Lugari",
  "Likuyani": "Likuyani",
  "Malava": "Butali/Chegulo",
  "Lurambi": "Butsotso East",
  "Navakholo": "Bunyala Central",
  "Mumias West": "Mumias Central",
  "Mumias East": "East Wanga",
  "Matungu": "Koyonzo",
  "Butere": "Marama Central",
  "Khwisero": "Kisa Central",
  "Shinyalu": "Isukha Central",
  "Ikolomani": "Idakho South",
  "Vihiga": "Central Maragoli",
  "Sabatia": "Wodanga",
  "Hamisi": "Shiru",
  "Luanda": "Luanda Township",
  "Emuhaya": "Central Bunyore",
  "Teso North": "Malaba Central",
  "Teso South": "Amukura Central",
  "Nambale": "Nambale Township",
  "Matayos": "Bukhayo West",
  "Butula": "Elugulu",
  "Funyula": "Ageng'A Nanguba",
  "Budalangi": "Bunyala Central",
  "Alego Usonga": "Central Alego",
  "Gem": "Central Gem",
  "Bondo": "Central Sakwa",
  "Rarieda": "East Asembo",
  "Ugenya": "West Ugenya",
  "Ugunja": "Ugunja",
  "Kasipul": "West Kasipul",
  "Kabondo Kasipul": "Kabondo West",
  "Karachuonyo": "North Karachuonyo",
  "Rangwe": "East Gem",
  "Homa Bay Town": "Homa Bay Central",
  "Ndhiwa": "Kabuoch North",
  "Suba North": "Gembe",
  "Suba South": "Gwassi North",
  "Rongo": "Central Kamagambo",
  "Awendo": "North Sakwa",
  "Suna East": "Suna Central",
  "Suna West": "Wasimbete",
  "Uriri": "Central Kanyamkago",
  "Nyatike": "Kachien'G",
  "Kuria West": "Bukira Centrl/Ikerege",
  "Kuria East": "Gokeharaka/Getambwega",
  "Bonchari": "Bogiakumu",
  "South Mugirango": "Bogetenga",
  "Bomachoge Borabu": "Bokimonge",
  "Bobasi": "Basi Central",
  "Bomachoge Chache": "Boochi/Tendere",
  "Nyaribari Masaba": "Gesusu",
  "Nyaribari Chache": "Kisii Central",
  "Kitutu Chache North": "Monyerero",
  "Kitutu Chache South": "Kitutu Central",
  "Kitutu Masaba": "Gesima",
  "West Mugirango": "Bosamaro",
  "North Mugirango": "Bokeira",
  "Borabu": "Esise",
  "Tinderet": "Chemelil/Chemase",
  "Aldai": "Kemeloi-Maraba",
  "Nandi Hills": "Nandi Hills",
  "Chesumei": "Chemundu/Kapng'Etuny",
  "Emgwen": "Chepkumia",
  "Mosop": "Kabiyet",
  "Tiaty": "Tirioko",
  "Baringo North": "Bartabwa",
  "Baringo Central": "Ewalel/Chapchap",
  "Baringo South": "Ilchamus",
  "Eldama Ravine": "Koibatek",
  "Mogotio": "Mogotio",
  "Kipkelion East": "Chepseon",
  "Kipkelion West": "Kipkelion",
  "Ainamoi": "Ainamoi",
  "Belgut": "Waldai",
  "Sigowet/Soin": "Sigowet",
  "Bureti": "Cheboin",
  "Sotik": "Chemagel",
  "Chepalungu": "Kong'Asis",
  "Bomet East": "Chemaner",
  "Bomet Central": "Silibwet Township",
  "Konoin": "Kimulot",
  "Kilgoris": "Kilgoris Central",
  "Emurua Dikirr": "Ilkerin",
  "Narok North": "Narok Town",
  "Narok East": "Mosiro",
  "Narok South": "Majimoto/Naroosura",
  "Narok West": "Ilmotiok",
  "Marakwet East": "Embobut / Embulot",
  "Marakwet West": "Arror",
  "Keiyo North": "Emsoo",
  "Keiyo South": "Chepkorio",
  "Msambweni": "Gombato Bongwe",
  "Lungalunga": "Dzombo",
  "Matuga": "Tsimba Golini",
  "Kinango": "Ndavaya",
  "Taveta": "Bomani",
  "Wundanyi": "Wundanyi/Mbale",
  "Mwatate": "Mwatate",
  "Voi": "Kaloleni",
  "Garsen": "Garsen Central",
  "Galole": "Wayu",
  "Bura": "Bangale",
  "Lamu East": "Faza",
  "Lamu West": "Bahari",
  "Maara": "Chogoria",
  "Tharaka": "Chiakariga",
  "Chuka/Igambang'Ombe": "Igambang'Ombe",
  "Isiolo North": "Burat",
  "Isiolo South": "Garbatulla",
  "Laisamis": "Logo Logo",
  "Moyale": "Moyale Township",
  "North Horr": "Dukana",
  "Saku": "Marsabit Central",
  "Samburu North": "El-Barta",
  "Samburu East": "Waso",
  "Samburu West": "Lodokejek",
  "Turkana North": "Lapur",
  "Turkana West": "Kalobeyei",
  "Turkana Central": "Lodwar Township",
  "Loima": "Loima",
  "Turkana South": "Kaputir",
  "Turkana East": "Kapedo/Napeitom",
  "Kacheliba": "Alale",
  "Pokot South": "Batei",
  "Kapenguria": "Kapenguria",
  "Sigor": "Sekerr",
  "Fafi": "Nanighi",
  "Ijara": "Ijara",
  "Dadaab": "Dadaab",
  "Balambala": "Balambala",
  "Lagdera": "Modogashe",
  "Garissa Township": "Township",
  "Wajir North": "Batalu",
  "Wajir East": "Barwago",
  "Wajir West": "Adamasajide",
  "Wajir South": "Benane",
  "Tarbaj": "Tarbaj",
  "Eldas": "Eldas",
  "Mandera North": "Ashabito",
  "Mandera South": "Elwak North",
  "Mandera East": "Township",
  "Mandera West": "Dandu",
  "Lafey": "Lafey",
  "Banissa": "Banissa",
  "Mbooni": "Mbooni",
  "Kaiti": "Ilima",
  "Makueni": "Wote",
  "Kibwezi West": "Emali/Mulala",
  "Kibwezi East": "Mtito Andei",
  "Kilome": "Kasikeu",
  "Mwingi North": "Ngomeni",
  "Mwingi West": "Kiomo/Kyethani",
  "Mwingi Central": "Central",
  "Kitui West": "Mutonguni",
  "Kitui Rural": "Kanyangi",
  "Kitui Central": "Township",
  "Kitui East": "Zombe/Mwitika",
  "Kitui South": "Athi",
}
