// Auto-generated from IEBC official polling station CSV files
// Source: /public/polling-stations/*.csv

export const COUNTY_CONSTITUENCIES: Record<string, string[]> = {
  "Baringo": ["Baringo Central","Baringo North","Baringo South","Eldama Ravine","Mogotio","Tiaty"],
  "Bomet": ["Bomet Central","Bomet East","Chepalungu","Konoin","Sotik"],
  "Bungoma": ["Bumula","Kabuchai","Kanduyi","Kimilili","Mt. Elgon","Sirisia","Tongaren","Webuye East","Webuye West"],
  "Busia": ["Budalangi","Butula","Funyula","Matayos","Nambale","Teso North","Teso South"],
  "Elgeyo-Marakwet": ["Keiyo North","Keiyo South","Marakwet East","Marakwet West"],
  "Embu": ["Manyatta","Mbeere North","Mbeere South","Runyenjes"],
  "Garissa": ["Balambala","Dadaab","Fafi","Garissa Township","Ijara","Lagdera"],
  "Homa Bay": ["Homa Bay Town","Kabondo Kasipul","Karachuonyo","Kasipul","Ndhiwa","Rangwe","Suba North","Suba South"],
  "Isiolo": ["Isiolo North","Isiolo South"],
  "Kajiado": ["Kajiado Central","Kajiado East","Kajiado North","Kajiado South","Kajiado West"],
  "Kakamega": ["Butere","Ikolomani","Khwisero","Likuyani","Lugari","Lurambi","Malava","Matungu","Mumias East","Mumias West","Navakholo","Shinyalu"],
  "Kericho": ["Ainamoi","Belgut","Bureti","Kipkelion East","Kipkelion West","Sigowet/Soin"],
  "Kiambu": ["Gatundu North","Gatundu South","Githunguri","Juja","Kabete","Kiambaa","Kiambu","Kikuyu","Lari","Limuru","Ruiru","Thika Town"],
  "Kilifi": ["Ganze","Kaloleni","Kilifi North","Kilifi South","Magarini","Malindi","Rabai"],
  "Kirinyaga": ["Gichugu","Kirinyaga Central","Mwea","Ndia"],
  "Kisii": ["Bobasi","Bomachoge Borabu","Bomachoge Chache","Bonchari","Kitutu Chache North","Kitutu Chache South","Nyaribari Chache","Nyaribari Masaba","South Mugirango"],
  "Kisumu": ["Kisumu Central","Kisumu East","Kisumu West","Muhoroni","Nyakach","Nyando","Seme"],
  "Kitui": ["Kitui Central","Kitui East","Kitui Rural","Kitui South","Kitui West","Mwingi Central","Mwingi North","Mwingi West"],
  "Kwale": ["Kinango","Lungalunga","Matuga","Msambweni"],
  "Laikipia": ["Laikipia East","Laikipia North","Laikipia West"],
  "Lamu": ["Lamu East","Lamu West"],
  "Machakos": ["Kangundo","Kathiani","Machakos Town","Masinga","Matungulu","Mavoko","Mwala","Yatta"],
  "Makueni": ["Kaiti","Kibwezi East","Kibwezi West","Kilome","Makueni","Mbooni"],
  "Mandera": ["Banissa","Lafey","Mandera East","Mandera North","Mandera South","Mandera West"],
  "Marsabit": ["Laisamis","Moyale","North Horr","Saku"],
  "Meru": ["Buuri","Central Imenti","Igembe Central","Igembe North","Igembe South","North Imenti","South Imenti","Tigania East","Tigania West"],
  "Migori": ["Awendo","Kuria East","Kuria West","Nyatike","Rongo","Suna East","Suna West","Uriri"],
  "Mombasa": ["Changamwe","Jomvu","Kisauni","Likoni","Mvita","Nyali"],
  "Murang'a": ["Gatanga","Kandara","Kangema","Kigumo","Kiharu","Maragwa","Mathioya"],
  "Nairobi": ["Dagoretti North","Dagoretti South","Embakasi Central","Embakasi East","Embakasi North","Embakasi South","Embakasi West","Kamukunji","Kasarani","Kibra","Langata","Makadara","Mathare","Roysambu","Ruaraka","Starehe","Westlands"],
  "Nakuru": ["Bahati","Gilgil","Kuresoi North","Kuresoi South","Molo","Naivasha","Nakuru Town East","Nakuru Town West","Njoro","Rongai","Subukia"],
  "Nandi": ["Aldai","Chesumei","Emgwen","Mosop","Nandi Hills","Tinderet"],
  "Narok": ["Emurua Dikirr","Kilgoris","Narok East","Narok North","Narok South","Narok West"],
  "Nyamira": ["Borabu","Kitutu Masaba","North Mugirango","West Mugirango"],
  "Nyandarua": ["Kinangop","Kipipiri","Ndaragwa","Ol Jorok","Ol Kalou"],
  "Nyeri": ["Kieni","Mathira","Mukurweini","Nyeri Town","Othaya","Tetu"],
  "Samburu": ["Samburu East","Samburu North","Samburu West"],
  "Siaya": ["Alego Usonga","Bondo","Gem","Rarieda","Ugenya","Ugunja"],
  "Taita Taveta": ["Mwatate","Taveta","Voi","Wundanyi"],
  "Tana River": ["Bura","Galole","Garsen"],
  "Tharaka-Nithi": ["Chuka/Igambang'Ombe","Maara","Tharaka"],
  "Trans Nzoia": ["Cherangany","Endebess","Kiminini","Kwanza","Saboti"],
  "Turkana": ["Loima","Turkana Central","Turkana East","Turkana North","Turkana South","Turkana West"],
  "Uasin Gishu": ["Ainabkoi","Kapseret","Kesses","Moiben","Soy","Turbo"],
  "Vihiga": ["Emuhaya","Hamisi","Luanda","Sabatia","Vihiga"],
  "Wajir": ["Eldas","Tarbaj","Wajir East","Wajir North","Wajir South","Wajir West"],
  "West Pokot": ["Kacheliba","Kapenguria","Pokot South","Sigor"],
}

export const COUNTIES = Object.keys(COUNTY_CONSTITUENCIES).sort()

export const CONSTITUENCY_WARDS: Record<string, string[]> = {
  "Baringo Central": ["Ewalel/Chapchap","Kabarnet","Kapropita","Sacho","Tenges"],
  "Baringo North": ["Bartabwa","Barwessa","Kabartonjo","Saimo/Kipsaraman","Saimo/Soi"],
  "Baringo South": ["Ilchamus","Marigat","Mochongoi","Mukutani"],
  "Eldama Ravine": ["Koibatek","Lembus","Lembus Kwen","Lembus/Perkerra","Mumberes/Maji Mazuri","Ravine"],
  "Mogotio": ["Emining","Kisanana","Mogotio"],
  "Tiaty": ["Churo/Amaya","Kolowa","Loiyamorock","Ribkwo","Silale","Tangulbei/Korossi","Tirioko"],
  "Bomet Central": ["Chesoen","Mutarakwa","Ndaraweta","Silibwet Township","Singorwet"],
  "Bomet East": ["Chemaner","Kembu","Kipreres","Longisa","Merigi"],
  "Chepalungu": ["Chebunyo","Kong'Asis","Nyangores","Sigor","Siongiroi"],
  "Konoin": ["Boito","Chepchabas","Embomos","Kimulot","Mogogosiek"],
  "Sotik": ["Chemagel","Kapletundo","Kipsonoi","Ndanai/Abosi","Rongena/Manaret"],
  "Bumula": ["Bumula","Kabula","Khasoko","Kimaeti","Siboti","South Bukusu","West Bukusu"],
  "Kabuchai": ["Bwake/Luuya","Kabuchai/Chwele","Mukuyuni","West Nalondo"],
  "Kanduyi": ["Bukembe East","Bukembe West","East Sang'Alo","Khalaba","Marakaru/Tuuti","Musikoma","Township","West Sang'Alo"],
  "Kimilili": ["Kamukuywa","Kibingei","Kimilili","Maeni"],
  "Mt. Elgon": ["Cheptais","Chepyuk","Chesikaki","Elgon","Kapkateny","Kaptama"],
  "Sirisia": ["Lwandanyi","Malakisi/South Kulisiru","Namwela"],
  "Tongaren": ["Mbakalo","Milima","Naitiri/Kabuyefwe","Ndalu/ Tabani","Soysambu/ Mitua","Tongaren"],
  "Webuye East": ["Maraka","Mihuu","Ndivisi"],
  "Webuye West": ["Bokoli","Matulo","Misikhu","Sitikho"],
  "Budalangi": ["Bunyala Central","Bunyala North","Bunyala South","Bunyala West"],
  "Butula": ["Elugulu","Kingandole","Marachi Central","Marachi East","Marachi North","Marachi West"],
  "Funyula": ["Ageng'A Nanguba","Bwiri","Namboboto Nambuku","Nangina"],
  "Matayos": ["Bukhayo West","Burumba","Busibwabo","Matayos South","Mayenje"],
  "Nambale": ["Bukhayo Central","Bukhayo East","Bukhayo North/Waltsi","Nambale Township"],
  "Teso North": ["Ang'Urai East","Ang'Urai North","Ang'Urai South","Malaba Central","Malaba North","Malaba South"],
  "Teso South": ["Amukura Central","Amukura East","Amukura West","Ang'Orom","Chakol North","Chakol South"],
  "Keiyo North": ["Emsoo","Kamariny","Kapchemutwa","Tambach"],
  "Keiyo South": ["Chepkorio","Kabiemit","Kaptarakwa","Metkei","Soy North","Soy South"],
  "Marakwet East": ["Embobut / Embulot","Endo","Kapyego","Sambirir"],
  "Marakwet West": ["Arror","Cherang'Any/Chebororwa","Kapsowar","Lelan","Moiben/Kuserwo","Sengwer"],
  "Manyatta": ["Gaturi South","Kirimari","Kithimu","Mbeti North","Nginda","Ruguru/Ngandori"],
  "Mbeere North": ["Evurore","Muminji","Nthawa"],
  "Mbeere South": ["Kiambere","Makima","Mavuria","Mbeti South","Mwea"],
  "Runyenjes": ["Central Ward","Gaturi North","Kagaari North","Kagaari South","Kyeni North","Kyeni South"],
  "Balambala": ["Balambala","Danyere","Jara Jara","Saka","Sankuri"],
  "Dadaab": ["Abakaile","Dadaab","Damajale","Dertu","Labasigale","Liboi"],
  "Fafi": ["Bura","Dekaharia","Fafi","Jarajila","Nanighi"],
  "Garissa Township": ["Galbet","Iftin","Township","Waberi"],
  "Ijara": ["Hulugho","Ijara","Masalani","Sangailu"],
  "Lagdera": ["Baraki","Benane","Goreale","Maalimin","Modogashe","Sabena"],
  "Homa Bay Town": ["Homa Bay Arujo","Homa Bay Central","Homa Bay East","Homa Bay West"],
  "Kabondo Kasipul": ["Kabondo East","Kabondo West","Kojwach","Kokwanyo/Kakelo"],
  "Karachuonyo": ["Central","Kanyaluo","Kendu Bay Town","Kibiri","North Karachuonyo","Wangchieng","West Karachuonyo"],
  "Kasipul": ["Central Kasipul","East Kamagak","South Kasipul","West Kamagak","West Kasipul"],
  "Ndhiwa": ["Kabuoch North","Kabuoch South/Pala","Kanyadoto","Kanyamwa Kologi","Kanyamwa Kosewe","Kanyikela","Kwabwai"],
  "Rangwe": ["East Gem","Kagan","Kochia","West Gem"],
  "Suba North": ["Gembe","Kasgunga","Lambwe","Mfangano Island","Rusinga Island"],
  "Suba South": ["Gwassi North","Gwassi South","Kaksingri West","Ruma-Kaksingri"],
  "Isiolo North": ["Bulla Pesa","Burat","Chari","Cherab","Ngare Mara","Oldo/Nyiro","Wabera"],
  "Isiolo South": ["Garbatulla","Kinna","Sericho"],
  "Kajiado Central": ["Dalalekutuk","Ildamat","Matapato North","Matapato South","Purko"],
  "Kajiado East": ["Imaroro","Kaputiei North","Kenyawa-Poka","Kitengela","Oloosirkon/Sholinke"],
  "Kajiado North": ["Ngong","Nkaimurunya","Olkeri","Oloolua","Ongata Rongai"],
  "Kajiado South": ["Entonet/Lenkisim","Kimana","Kuku","Mbirikani/Eselenkei","Rombo"],
  "Kajiado West": ["Ewuaso Oonkidong'I","Iloodokilani","Keekonyokie","Magadi","Mosiro"],
  "Butere": ["Marama Central","Marama North","Marama South","Marama West","Marenyo - Shianda"],
  "Ikolomani": ["Idakho Central","Idakho East","Idakho North","Idakho South"],
  "Khwisero": ["Kisa Central","Kisa East","Kisa North","Kisa West"],
  "Likuyani": ["Kongoni","Likuyani","Nzoia","Sango","Sinoko"],
  "Lugari": ["Chekalini","Chevaywa","Lugari","Lumakanda","Lwandeti","Mautuma"],
  "Lurambi": ["Butsotso Central","Butsotso East","Butsotso South","Mahiakalo","Sheywe","Shirere"],
  "Malava": ["Butali/Chegulo","Chemuche","East Kabras","Manda-Shivanga","Shirugu-Mugai","South Kabras","West Kabras"],
  "Matungu": ["Khalaba","Kholera","Koyonzo","Mayoni","Namamali"],
  "Mumias East": ["East Wanga","Lusheya/Lubinu","Malaha/Isongo/Makunga"],
  "Mumias West": ["Etenje","Mumias Central","Mumias North","Musanda"],
  "Navakholo": ["Bunyala Central","Bunyala East","Bunyala West","Ingostse-Mathia","Shinoyi-Shikomari-Esumeyia"],
  "Shinyalu": ["Isukha Central","Isukha East","Isukha North","Isukha South","Isukha West","Murhanda"],
  "Ainamoi": ["Ainamoi","Kapkugerwet","Kapsaos","Kapsoit","Kipchebor","Kipchimchim"],
  "Belgut": ["Chaik","Cheptororiet/Seretut","Kabianga","Kapsuser","Waldai"],
  "Bureti": ["Cheboin","Chemosot","Cheplanget","Kapkatet","Kisiara","Litein","Tebesonik"],
  "Kipkelion East": ["Chepseon","Kedowa/Kimugul","Londiani","Tendeno/Sorget"],
  "Kipkelion West": ["Chilchila","Kamasian","Kipkelion","Kunyak"],
  "Sigowet/Soin": ["Kaplelartet","Sigowet","Soin","Soliat"],
  "Gatundu North": ["Chania","Githobokoni","Gituamba","Mang'U"],
  "Gatundu South": ["Kiamwangi","Kiganjo","Ndarugu","Ngenda"],
  "Githunguri": ["Githiga","Githunguri","Ikinu","Komothai","Ngewa"],
  "Juja": ["Juja","Kalimoni","Murera","Theta","Witeithie"],
  "Kabete": ["Gitaru","Kabete","Muguga","Nyadhuna","Uthiru"],
  "Kiambaa": ["Cianda","Karuri","Kihara","Muchatha","Ndenderu"],
  "Kiambu": ["Ndumberi","Riabai","Ting'Ang'A","Township"],
  "Kikuyu": ["Karai","Kikuyu","Kinoo","Nachu","Sigona"],
  "Lari": ["Kamburu","Kijabe","Kinale","Lari/Kirenga","Nyanduma"],
  "Limuru": ["Bibirioni","Limuru Central","Limuru East","Ndeiya","Ngecha Tigoni"],
  "Ruiru": ["Biashara","Gatongora","Gitothua","Kahawa Sukari","Kahawa Wendani","Kiuu","Mwihoko","Mwiki"],
  "Thika Town": ["Gatuanyaga","Hospital","Kamenu","Ngoliba","Township"],
  "Ganze": ["Bamba","Ganze","Jaribuni","Sokoke"],
  "Kaloleni": ["Kaloleni","Kayafungo","Mariakani","Mwanamwinga"],
  "Kilifi North": ["Dabaso","Kibarani","Matsangoni","Mnarani","Sokoni","Tezo","Watamu"],
  "Kilifi South": ["Chasimba","Junju","Mtepeni","Mwarakaya","Shimo La Tewa"],
  "Magarini": ["Adu","Garashi","Gongoni","Magarini","Marafa","Sabaki"],
  "Malindi": ["Ganda","Jilore","Kakuyuni","Malindi Town","Shella"],
  "Rabai": ["Kambe/Ribe","Mwawesa","Rabai/Kisurutini","Ruruma"],
  "Gichugu": ["Baragwi","Kabare","Karumandi","Ngariama","Njukiini"],
  "Kirinyaga Central": ["Inoi","Kanyekini","Kerugoya","Mutira"],
  "Mwea": ["Gathigiriri","Kangai","Murinduko","Mutithi","Nyangati","Tebere","Thiba","Wamumu"],
  "Ndia": ["Kariti","Kiine","Mukure"],
  "Bobasi": ["Basi Bogetaorio","Basi Central","Bobasi Boitangare","Bobasi Chache","Masige East","Masige West","Nyacheki","Sameta/Mokwerero"],
  "Bomachoge Borabu": ["Bokimonge","Bombaba Borabu","Boochi Borabu","Magenche"],
  "Bomachoge Chache": ["Boochi/Tendere","Bosoti/Sengera","Majoge Basi"],
  "Bonchari": ["Bogiakumu","Bomariba","Bomorenda","Riana"],
  "Kitutu Chache North": ["Kegogi","Marani","Monyerero","Sensi"],
  "Kitutu Chache South": ["Bogeka","Bogusero","Kitutu Central","Nyakoe","Nyatieko"],
  "Nyaribari Chache": ["Birongo","Bobaracho","Ibeno","Keumbu","Kiogoro","Kisii Central"],
  "Nyaribari Masaba": ["Gesusu","Ichuni","Kiamokama","Masimba","Nyamasibi"],
  "South Mugirango": ["Bogetenga","Boikang'A","Borabu / Chitago","Getenga","Moticho","Tabaka"],
  "Kisumu Central": ["Kondele","Market Milimani","Migosi","Nyalenda B","Railways","Shaurimoyo Kaloleni"],
  "Kisumu East": ["Kajulu","Kolwa Central","Kolwa East","Manyatta 'B'","Nyalenda 'A'"],
  "Kisumu West": ["Central Kisumu","Kisumu North","North West Kisumu","South West Kisumu","West Kisumu"],
  "Muhoroni": ["Chemelil","Masogo/Nyang'Oma","Miwani","Muhoroni/Koru","Ombeyi"],
  "Nyakach": ["Central Nyakach","North Nyakach","South East Nyakach","South West Nyakach","West Nyakach"],
  "Nyando": ["Ahero","Awasi/Onjiko","East Kano/Wawidhi","Kabonyo/Kanyagwal","Kobura"],
  "Seme": ["Central Seme","East Seme","North Seme","West Seme"],
  "Kitui Central": ["Kyangwithya East","Kyangwithya West","Miambani","Mulango","Township"],
  "Kitui East": ["Chuluni","Endau/Malalani","Mutito/Kaliku","Nzambani","Voo/Kyamatu","Zombe/Mwitika"],
  "Kitui Rural": ["Kanyangi","Kisasi","Kwavonza/Yatta","Mbitini"],
  "Kitui South": ["Athi","Ikanga/Kyatune","Ikutha","Kanziko","Mutha","Mutomo"],
  "Kitui West": ["Kauwi","Kwa Mutonga/Kithumula","Matinyani","Mutonguni"],
  "Mwingi Central": ["Central","Kivou","Mui","Nguni","Nuu","Waita"],
  "Mwingi North": ["Kyuso","Mumoni","Ngomeni","Tharaka","Tseikuru"],
  "Mwingi West": ["Kiomo/Kyethani","Kyome/Thaana","Migwani","Nguutani"],
  "Kinango": ["Chengoni/Samburu","Kasemeni","Kinango","Mackinnon Road","Mwavumbo","Ndavaya","Puma"],
  "Lungalunga": ["Dzombo","Mwereni","Pongwe/Kikoneni","Vanga"],
  "Matuga": ["Kubo South","Mkongani","Tiwi","Tsimba Golini","Waa"],
  "Msambweni": ["Gombato Bongwe","Kinondo","Ramisi","Ukunda"],
  "Laikipia East": ["Nanyuki","Ngobit","Thingithu","Tigithi","Umande"],
  "Laikipia North": ["Mugogodo East","Mugogodo West","Segera","Sosian"],
  "Laikipia West": ["Githiga","Igwamiti","Marmanet","Ol-Moran","Rumuruti Township","Salama"],
  "Lamu East": ["Basuba","Faza","Kiunga"],
  "Lamu West": ["Bahari","Hindi","Hongwe","Mkomani","Mkunumbi","Shella","Witu"],
  "Kangundo": ["Kangundo Central","Kangundo East","Kangundo North","Kangundo West"],
  "Kathiani": ["Kathiani Central","Lower Kaewa/Kaani","Mitaboni","Upper Kaewa/Iveti"],
  "Machakos Town": ["Kalama","Kola","Machakos Central","Mua","Mumbuni North","Mutituni","Muvuti/Kiima-Kimwe"],
  "Masinga": ["Ekalakala","Kivaa","Masinga Central","Muthesya","Ndithini"],
  "Matungulu": ["Kyeleni","Matungulu East","Matungulu North","Matungulu West","Tala"],
  "Mavoko": ["Athi River","Kinanie","Muthwani","Syokimau/Mulolongo"],
  "Mwala": ["Kibauni","Makutano/ Mwala","Masii","Mbiuni","Muthetheni","Wamunyu"],
  "Yatta": ["Ikombe","Katangi","Kithimani","Matuu","Ndalani"],
  "Kaiti": ["Ilima","Kee","Kilungu","Ukia"],
  "Kibwezi East": ["Ivingoni/Nzambani","Masongaleni","Mtito Andei","Thange"],
  "Kibwezi West": ["Emali/Mulala","Kikumbulyu North","Kikumbulyu South","Makindu","Nguu/Masumba","Nguumo"],
  "Kilome": ["Kasikeu","Kiima Kiu/Kalanzoni","Mukaa"],
  "Makueni": ["Kathonzweni","Kitise/Kithuki","Mavindini","Mbitini","Muvau/Kikuumini","Nzaui/Kilili/Kalamba","Wote"],
  "Mbooni": ["Kalawa","Kiteta/Kisau","Kithungo/Kitundu","Mbooni","Tulimani","Waia-Kako"],
  "Banissa": ["Banissa","Derkhale","Guba","Kiliwehiri","Malkamari"],
  "Lafey": ["Alango Gof","Fino","Lafey","Sala","Waranqara"],
  "Mandera East": ["Arabia","Khalalio","Libehia","Neboi","Township"],
  "Mandera North": ["Ashabito","Guticha","Morothile","Rhamu","Rhamu-Dimtu"],
  "Mandera South": ["Elwak North","Elwak South","Kutulo","Shimbir Fatuma","Wargadud"],
  "Mandera West": ["Dandu","Gither","Lagsure","Takaba","Takaba South"],
  "Laisamis": ["Kargi/South Horr","Korr/Ngurunit","Laisamis","Logo Logo","Loiyangalani"],
  "Moyale": ["Butiye","Golbo","Heillu/Manyatta","Moyale Township","Obbu","Sololo","Uran"],
  "North Horr": ["Dukana","Illeret","Maikona","North Horr","Turbi"],
  "Saku": ["Karare","Marsabit Central","Sagante/Jaldesa"],
  "Buuri": ["Kibirichia","Kiirua/Naari","Kisima","Ruiri/Rwarera","Timau"],
  "Central Imenti": ["Abothuguchi Central","Abothuguchi West","Kiagu","Mwanganthia"],
  "Igembe Central": ["Akirang'Ondu","Athiru Ruujine","Igembe East","Kangeta","Njia"],
  "Igembe North": ["Amwathi","Antuambui","Antubetwe Kiongo","Naathu","Ntunene"],
  "Igembe South": ["Akachiu","Athiru Gaiti","Kanuni","Kiegoi/Antubochiu","Maua"],
  "North Imenti": ["Municipality","Ntima East","Ntima West","Nyaki East","Nyaki West"],
  "South Imenti": ["Abogeta East","Abogeta West","Igoji East","Igoji West","Mitunguu","Nkuene"],
  "Tigania East": ["Karama","Kiguchwa","Mikinduri","Muthara","Thangatha"],
  "Tigania West": ["Akithii","Athwana","Kianjai","Mbeu","Nkomo"],
  "Awendo": ["Central Sakwa","North Sakwa","South Sakwa","West Sakwa"],
  "Kuria East": ["Gokeharaka/Getambwega","Ntimaru East","Ntimaru West","Nyabasi East","Nyabasi West"],
  "Kuria West": ["Bukira Centrl/Ikerege","Bukira East","Isibania","Makerero","Masaba","Nyamosense/Komosoko","Tagare"],
  "Nyatike": ["Got Kachola","Kachien'G","Kaler","Kanyasa","Macalder/Kanyarwanda","Muhuru","North Kadem"],
  "Rongo": ["Central Kamagambo","East Kamagambo","North Kamagambo","South Kamagambo"],
  "Suna East": ["God Jope","Kakrao","Kwa","Suna Central"],
  "Suna West": ["Ragana-Oruba","Wasimbete","Wasweta Ii","Wiga"],
  "Uriri": ["Central Kanyamkago","East Kanyamkago","North Kanyamkago","South Kanyamkago","West Kanyamkago"],
  "Changamwe": ["Airport","Chaani","Changamwe","Kipevu","Port Reitz"],
  "Jomvu": ["Jomvu Kuu","Mikindani","Miritini"],
  "Kisauni": ["Bamburi","Junda","Magogoni","Mjambere","Mtopanga","Mwakirunge","Shanzu"],
  "Likoni": ["Bofu","Likoni","Mtongwe","Shika Adabu","Timbwani"],
  "Mvita": ["Majengo","Mji Wa Kale/Makadara","Shimanzi/Ganjoni","Tononoka","Tudor"],
  "Nyali": ["Frere Town","Kadzandani","Kongowea","Mkomani","Ziwa La Ng'Ombe"],
  "Gatanga": ["Gatanga","Ithanga","Kakuzi/Mitubiri","Kariara","Kihumbu-Ini","Mugumo-Ini"],
  "Kandara": ["Gaichanjiru","Ithiru","Kagundu-Ini","Muruka","Ng'Araria","Ruchu"],
  "Kangema": ["Kanyenya-Ini","Muguru","Rwathia"],
  "Kigumo": ["Kahumbu","Kangari","Kigumo","Kinyona","Muthithi"],
  "Kiharu": ["Gaturi","Mbiri","Mugoiri","Murarandia","Township","Wangu"],
  "Maragwa": ["Ichagaki","Kamahuha","Kambiti","Kimorori/Wempa","Makuyu","Nginda"],
  "Mathioya": ["Gitugi","Kamacharia","Kiru"],
  "Dagoretti North": ["Gatina","Kabiro","Kawangware","Kileleshwa","Kilimani"],
  "Dagoretti South": ["Mutu-Ini","Ngando","Riruta","Uthiru/Ruthimitu","Waithaka"],
  "Embakasi Central": ["Kayole Central","Kayole North","Kayole South","Komarock","Matopeni/Spring Valley"],
  "Embakasi East": ["Embakasi","Lower Savannah","Mihango","Upper Savannah","Utawala"],
  "Embakasi North": ["Dandora Area I","Dandora Area Ii","Dandora Area Iii","Dandora Area Iv","Kariobangi North"],
  "Embakasi South": ["Imara Daima","Kwa Njenga","Kwa Reuben","Kware","Pipeline"],
  "Embakasi West": ["Kariobangi South","Mowlem","Umoja I","Umoja Ii"],
  "Kamukunji": ["Airbase","California","Eastleigh North","Eastleigh South","Pumwani"],
  "Kasarani": ["Clay City","Kasarani","Mwiki","Njiru","Ruai"],
  "Kibra": ["Laini Saba","Lindi","Makina","Sarangombe","Woodley/Kenyatta Golf Cou"],
  "Langata": ["Karen","Mugumu-Ini","Nairobi West","Nyayo Highrise","South C"],
  "Makadara": ["Harambee","Makongeni","Maringo/Hamza","Viwandani"],
  "Mathare": ["Hospital","Huruma","Kiamaiko","Mabatini","Mlango Kubwa","Ngei"],
  "Roysambu": ["Githurai","Kahawa","Kahawa West","Roysambu","Zimmerman"],
  "Ruaraka": ["Baba Dogo","Korogocho","Lucky Summer","Mathare North","Utalii"],
  "Starehe": ["Landimawe","Nairobi Central","Nairobi South","Ngara","Pangani","Ziwani/Kariokor"],
  "Westlands": ["Kangemi","Karura","Kitisuru","Mountain View","Parklands/Highridge"],
  "Bahati": ["Bahati","Dundori","Kabatini","Kiamaina","Lanet/Umoja"],
  "Gilgil": ["Elementaita","Gilgil","Malewa West","Mbaruk/Eburu","Murindati"],
  "Kuresoi North": ["Kamara","Kiptororo","Nyota","Sirikwa"],
  "Kuresoi South": ["Amalo","Keringet","Kiptagich","Tinet"],
  "Molo": ["Elburgon","Mariashoni","Molo","Turi"],
  "Naivasha": ["Biashara","Hells Gate","Lake View","Mai Mahiu","Maiella","Naivasha East","Olkaria","Viwandani"],
  "Nakuru Town East": ["Biashara","Flamingo","Kivumbini","Menengai","Nakuru East"],
  "Nakuru Town West": ["Barut","Kapkures","Kaptembwo","London","Rhoda","Shaabab"],
  "Njoro": ["Kihingo","Lare","Mau Narok","Mauche","Nessuit","Njoro"],
  "Rongai": ["Menengai West","Mosop","Soin","Solai","Visoi"],
  "Subukia": ["Kabazi","Subukia","Waseges"],
  "Aldai": ["Kabwareng","Kaptumo-Kaboi","Kemeloi-Maraba","Kobujoi","Koyo-Ndurio","Terik"],
  "Chesumei": ["Chemundu/Kapng'Etuny","Kaptel/Kamoiywo","Kiptuya","Kosirai","Lelmokwo/Ngechek"],
  "Emgwen": ["Chepkumia","Kapkangani","Kapsabet","Kilibwoni"],
  "Mosop": ["Chepterwai","Kabisaga","Kabiyet","Kipkaren","Kurgung/Surungai","Ndalat","Sangalo/Kebulonik"],
  "Nandi Hills": ["Chepkunyuk","Kapchorua","Nandi Hills","Ol'Lessos"],
  "Tinderet": ["Chemelil/Chemase","Kapsimotwo","Songhor/Soba","Tindiret"],
  "Emurua Dikirr": ["Ilkerin","Kapsasian","Mogondo","Ololmasani"],
  "Kilgoris": ["Angata Barikoi","Keyian","Kilgoris Central","Kimintet","Lolgorian","Shankoe"],
  "Narok East": ["Ildamat","Keekonyokie","Mosiro","Suswa"],
  "Narok North": ["Melili","Narok Town","Nkareta","Olokurto","Olorropil","Olpusimoru"],
  "Narok South": ["Loita","Majimoto/Naroosura","Melelo","Ololulung'A","Sagamian","Sogoo"],
  "Narok West": ["Ilmotiok","Mara","Naikarra","Siana"],
  "Borabu": ["Esise","Kiabonyoru","Mekenene","Nyansiongo"],
  "Kitutu Masaba": ["Gachuba","Gesima","Kemera","Magombo","Manga","Rigoma"],
  "North Mugirango": ["Bokeira","Bomwagamo","Ekerenyo","Itibo","Magwagwa"],
  "West Mugirango": ["Bogichora","Bonyamatuta","Bosamaro","Nyamaiya","Township"],
  "Kinangop": ["Engineer","Gathara","Githabai","Magumu","Murungaru","Njabini\\Kiburu","North Kinangop","Nyakio"],
  "Kipipiri": ["Geta","Githioro","Kipipiri","Wanjohi"],
  "Ndaragwa": ["Central","Kiriita","Leshau/Pondo","Shamata"],
  "Ol Jorok": ["Charagita","Gathanji","Gatimu","Weru"],
  "Ol Kalou": ["Kaimbaga","Kanjuiri Range","Karau","Mirangine","Rurii"],
  "Kieni": ["Gakawa","Gatarakwa","Kabaru","Mugunda","Mweiga","Mwiyogo/Endarasha","Naromoru Kiamathaga","Thegu River"],
  "Mathira": ["Iriaini","Karatina Town","Kirimukuyu","Konyu","Magutu","Ruguru"],
  "Mukurweini": ["Gikondi","Mukurwe-Ini Central","Mukurwe-Ini West","Rugi"],
  "Nyeri Town": ["Gatitu/Muruguru","Kamakwa/Mukaro","Kiganjo/Mathari","Ruring'U","Rware"],
  "Othaya": ["Chinga","Iria-Ini","Karima","Mahiga"],
  "Tetu": ["Aguthi-Gaaki","Dedan Kimanthi","Wamagana"],
  "Samburu East": ["Wamba East","Wamba North","Wamba West","Waso"],
  "Samburu North": ["Angata Nanyokie","Baawa","El-Barta","Nachola","Ndoto","Nyiro"],
  "Samburu West": ["Lodokejek","Loosuk","Maralal","Poro","Suguta Marmar"],
  "Alego Usonga": ["Central Alego","North Alego","Siaya Township","South East Alego","Usonga","West Alego"],
  "Bondo": ["Central Sakwa","North Sakwa","South Sakwa","West Sakwa","West Yimbo","Yimbo East"],
  "Gem": ["Central Gem","East Gem","North Gem","South Gem","West Gem","Yala Township"],
  "Rarieda": ["East Asembo","North Uyoma","South Uyoma","West Asembo","West Uyoma"],
  "Ugenya": ["East Ugenya","North Ugenya","Ukwala","West Ugenya"],
  "Ugunja": ["Sidindi","Sigomere","Ugunja"],
  "Mwatate": ["Bura","Chawia","Mwatate","Rong'E","Wusi/Kishamba"],
  "Taveta": ["Bomani","Chala","Mahoo","Mata","Mboghoni"],
  "Voi": ["Kaloleni","Kasigau","Marungu","Mbololo","Ngolia","Sagalla"],
  "Wundanyi": ["Mwanda/Mgange","Werugha","Wumingu/Kishushe","Wundanyi/Mbale"],
  "Bura": ["Bangale","Chewele","Hirimani","Madogo","Sala"],
  "Galole": ["Chewani","Kinakomba","Mikinduni","Wayu"],
  "Garsen": ["Garsen Central","Garsen North","Garsen South","Garsen West","Kipini East","Kipini West"],
  "Chuka/Igambang'Ombe": ["Igambang'Ombe","Karingani","Magumoni","Mariani","Mugwe"],
  "Maara": ["Chogoria","Ganga","Mitheru","Muthambi","Mwimbi"],
  "Tharaka": ["Chiakariga","Gatunga","Marimanti","Mukothima","Nkondi"],
  "Cherangany": ["Chepsiro/Kiptoror","Cherangany/Suwerwa","Kaplamai","Makutano","Motosiet","Sinyerere","Sitatunga"],
  "Endebess": ["Chepchoina","Endebess","Matumbei"],
  "Kiminini": ["Hospital","Kiminini","Nabiswa","Sikhendu","Sirende","Waitaluk"],
  "Kwanza": ["Bidii","Kapomboi","Keiyo","Kwanza"],
  "Saboti": ["Kinyoro","Machewa","Matisi","Saboti","Tuwani"],
  "Loima": ["Kotaruk/Lobei","Loima","Lokiriama/Lorengippi","Turkwel"],
  "Turkana Central": ["Kalokol","Kanamkemer","Kang'Atotha","Kerio Delta","Lodwar Township"],
  "Turkana East": ["Kapedo/Napeitom","Katilia","Lokori/Kochodin"],
  "Turkana North": ["Kaaleng/Kaikor","Kaeris","Kibish","Lake Zone","Lapur","Nakalale"],
  "Turkana South": ["Kalapata","Kaputir","Katilu","Lobokat","Lokichar"],
  "Turkana West": ["Kakuma","Kalobeyei","Letea","Lokichoggio","Lopur","Nanaam","Songot"],
  "Ainabkoi": ["Ainabkoi/Olare","Kapsoya","Kaptagat"],
  "Kapseret": ["Kipkenyo","Langas","Megun","Ngeria","Simat/Kapseret"],
  "Kesses": ["Cheptiret/Kipchamo","Racecourse","Tarakwa","Tulwet/Chuiyat"],
  "Moiben": ["Karuna/Meibeki","Kimumu","Moiben","Sergoit","Tembelio"],
  "Soy": ["Kapkures","Kipsomba","Kuinet/Kapsuswa","Moi'S Bridge","Segero/Barsombe","Soy","Ziwa"],
  "Turbo": ["Huruma","Kamagut","Kapsaos","Kiplombe","Ngenyilel","Tapsagoi"],
  "Emuhaya": ["Central Bunyore","North East Bunyore","West Bunyore"],
  "Hamisi": ["Banja","Gisambai","Jepkoyai","Muhudu","Shamakhokho","Shiru","Tambua"],
  "Luanda": ["Emabungo","Luanda South","Luanda Township","Mwibona","Wemilabi"],
  "Sabatia": ["Busali","Chavakali","Lyaduywa/Izava","North Maragoli","West Sabatia","Wodanga"],
  "Vihiga": ["Central Maragoli","Lugaga-Wamuluma","Mungoma","South Maragoli"],
  "Eldas": ["Della","Eldas","Elnur/Tula Tula","Lakoley South/Basir"],
  "Tarbaj": ["Elben","Sarman","Tarbaj","Wargadud"],
  "Wajir East": ["Barwago","Khorof/Harar","Township","Wagberi"],
  "Wajir North": ["Batalu","Bute","Danaba","Godoma","Gurar","Korondile","Malkagufu"],
  "Wajir South": ["Benane","Burder","Dadaja Bulla","Diif","Habasswein","Ibrahim Ure","Lagboghol South"],
  "Wajir West": ["Adamasajide","Arbajahan","Ganyure/Wagalla","Hadado/Athibohol"],
  "Kacheliba": ["Alale","Kapchok","Kasei","Kiwawa","Kodich","Suam"],
  "Kapenguria": ["Endugh","Kapenguria","Mnagei","Riwo","Siyoi","Sook"],
  "Pokot South": ["Batei","Chepareria","Lelan","Tapach"],
  "Sigor": ["Lomut","Masool","Sekerr","Weiwei"],
}
